/**
 * 실서비스용 큐레이션 품목 (검증된 KAMIS 코드)
 * 자유 검색 대신 “자주 쓰는 품목” 위주로 안정적으로 노출
 */

export type CuratedPriceChannel = 'retail' | 'wholesale';

export interface CuratedIngredient {
    /** UI / 검색용 표시명 */
    id: string;
    displayName: string;
    /** 검색 별칭 */
    aliases: string[];
    categoryCode: string;
    categoryName: string;
    itemCode: string;
    itemName: string;
    kindCode: string;
    kindName: string;
    unit: string;
    unitSize: string;
    rankCode: string;
    /** 기본 조회 채널 */
    channel: CuratedPriceChannel;
}

export const CURATED_INGREDIENTS: CuratedIngredient[] = [
    {
        id: 'rice',
        displayName: '쌀 (20kg)',
        aliases: ['쌀', '백미'],
        categoryCode: '100',
        categoryName: '식량작물',
        itemCode: '111',
        itemName: '쌀',
        kindCode: '01',
        kindName: '20kg',
        unit: 'kg',
        unitSize: '20',
        rankCode: '04',
        channel: 'retail',
    },
    {
        id: 'sweet-potato',
        displayName: '고구마',
        aliases: ['고구마', '밤고구마'],
        categoryCode: '100',
        categoryName: '식량작물',
        itemCode: '151',
        itemName: '고구마',
        kindCode: '00',
        kindName: '밤',
        unit: 'kg',
        unitSize: '1',
        rankCode: '04',
        channel: 'retail',
    },
    {
        id: 'potato',
        displayName: '감자',
        aliases: ['감자', '수미'],
        categoryCode: '100',
        categoryName: '식량작물',
        itemCode: '152',
        itemName: '감자',
        kindCode: '01',
        kindName: '수미(노지)',
        unit: 'kg',
        unitSize: '1',
        rankCode: '04',
        channel: 'retail',
    },
    {
        id: 'cabbage',
        displayName: '배추',
        aliases: ['배추'],
        categoryCode: '200',
        categoryName: '채소류',
        itemCode: '211',
        itemName: '배추',
        kindCode: '02',
        kindName: '여름(고랭지)',
        unit: '포기',
        unitSize: '1',
        rankCode: '04',
        channel: 'retail',
    },
    {
        id: 'spinach',
        displayName: '시금치',
        aliases: ['시금치'],
        categoryCode: '200',
        categoryName: '채소류',
        itemCode: '213',
        itemName: '시금치',
        kindCode: '00',
        kindName: '시금치',
        unit: 'kg',
        unitSize: '1',
        rankCode: '04',
        channel: 'retail',
    },
    {
        id: 'lettuce',
        displayName: '상추',
        aliases: ['상추'],
        categoryCode: '200',
        categoryName: '채소류',
        itemCode: '214',
        itemName: '상추',
        kindCode: '01',
        kindName: '청',
        unit: 'kg',
        unitSize: '1',
        rankCode: '04',
        channel: 'retail',
    },
    {
        id: 'cucumber',
        displayName: '오이',
        aliases: ['오이'],
        categoryCode: '200',
        categoryName: '채소류',
        itemCode: '223',
        itemName: '오이',
        kindCode: '01',
        kindName: '가시',
        unit: '개',
        unitSize: '10',
        rankCode: '04',
        channel: 'retail',
    },
    {
        id: 'zucchini',
        displayName: '애호박',
        aliases: ['호박', '애호박'],
        categoryCode: '200',
        categoryName: '채소류',
        itemCode: '224',
        itemName: '호박',
        kindCode: '01',
        kindName: '애호박',
        unit: '개',
        unitSize: '1',
        rankCode: '04',
        channel: 'retail',
    },
    {
        id: 'tomato',
        displayName: '토마토',
        aliases: ['토마토'],
        categoryCode: '200',
        categoryName: '채소류',
        itemCode: '225',
        itemName: '토마토',
        kindCode: '00',
        kindName: '토마토',
        unit: 'kg',
        unitSize: '1',
        rankCode: '04',
        channel: 'retail',
    },
    {
        id: 'radish',
        displayName: '무',
        aliases: ['무'],
        categoryCode: '200',
        categoryName: '채소류',
        itemCode: '231',
        itemName: '무',
        kindCode: '01',
        kindName: '봄',
        unit: '개',
        unitSize: '1',
        rankCode: '04',
        channel: 'retail',
    },
    {
        id: 'onion',
        displayName: '양파',
        aliases: ['양파'],
        categoryCode: '200',
        categoryName: '채소류',
        itemCode: '245',
        itemName: '양파',
        kindCode: '00',
        kindName: '양파',
        unit: 'kg',
        unitSize: '1',
        rankCode: '04',
        channel: 'retail',
    },
    {
        id: 'green-onion',
        displayName: '대파',
        aliases: ['대파', '파'],
        categoryCode: '200',
        categoryName: '채소류',
        itemCode: '246',
        itemName: '파',
        kindCode: '00',
        kindName: '대파',
        unit: 'kg',
        unitSize: '1',
        rankCode: '04',
        channel: 'retail',
    },
    {
        id: 'garlic',
        displayName: '깐마늘(국산)',
        aliases: ['마늘', '깐마늘', '피마늘'],
        categoryCode: '200',
        categoryName: '채소류',
        itemCode: '258',
        itemName: '깐마늘(국산)',
        kindCode: '01',
        kindName: '깐마늘(국산)',
        unit: 'kg',
        unitSize: '1',
        rankCode: '04',
        channel: 'retail',
    },
    {
        id: 'apple',
        displayName: '사과',
        aliases: ['사과'],
        categoryCode: '400',
        categoryName: '과일류',
        itemCode: '411',
        itemName: '사과',
        kindCode: '05',
        kindName: '후지',
        unit: '개',
        unitSize: '10',
        rankCode: '04',
        channel: 'retail',
    },
    {
        id: 'pear',
        displayName: '배',
        aliases: ['배'],
        categoryCode: '400',
        categoryName: '과일류',
        itemCode: '412',
        itemName: '배',
        kindCode: '01',
        kindName: '신고',
        unit: '개',
        unitSize: '10',
        rankCode: '04',
        channel: 'retail',
    },
    {
        id: 'banana',
        displayName: '바나나',
        aliases: ['바나나'],
        categoryCode: '400',
        categoryName: '과일류',
        itemCode: '418',
        itemName: '바나나',
        kindCode: '02',
        kindName: '수입',
        unit: 'kg',
        unitSize: '1',
        rankCode: '04',
        channel: 'retail',
    },
    {
        id: 'mackerel',
        displayName: '고등어',
        aliases: ['고등어'],
        categoryCode: '600',
        categoryName: '수산물',
        itemCode: '611',
        itemName: '고등어',
        kindCode: '01',
        kindName: '생선',
        unit: '마리',
        unitSize: '1',
        rankCode: '05',
        channel: 'wholesale',
    },
    {
        id: 'hairtail',
        displayName: '갈치',
        aliases: ['갈치'],
        categoryCode: '600',
        categoryName: '수산물',
        itemCode: '613',
        itemName: '갈치',
        kindCode: '01',
        kindName: '생선',
        unit: '마리',
        unitSize: '1',
        rankCode: '05',
        channel: 'wholesale',
    },
    {
        id: 'squid',
        displayName: '오징어',
        aliases: ['오징어', '물오징어'],
        categoryCode: '600',
        categoryName: '수산물',
        itemCode: '619',
        itemName: '물오징어',
        kindCode: '01',
        kindName: '생선',
        unit: '마리',
        unitSize: '1',
        rankCode: '05',
        channel: 'wholesale',
    },
    {
        id: 'hanwoo-sirloin',
        displayName: '한우 등심',
        aliases: ['소고기', '한우', '등심'],
        categoryCode: '500',
        categoryName: '축산물',
        itemCode: '4301',
        itemName: '소',
        kindCode: '21',
        kindName: '등심',
        unit: 'kg',
        unitSize: '1',
        rankCode: '01',
        channel: 'wholesale',
    },
];
